# Generated by Django 5.0.4 on 2024-05-20 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ShortURL",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성시간"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정시간"),
                ),
                (
                    "key",
                    models.CharField(max_length=6, primary_key=True, serialize=False),
                ),
                ("url", models.URLField(unique=True)),
                ("expired", models.DateTimeField(blank=True, null=True)),
                ("count", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "short_url",
            },
        ),
    ]
