# Generated by Django 5.0.4 on 2024-05-20 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shorturl", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="shorturl",
            old_name="expired",
            new_name="deleted_at",
        ),
        migrations.AddField(
            model_name="shorturl",
            name="expired_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
